### ISSUE TITLE
Pending Features

### ISSUE THREAD

**Issue by therealssj** [d8-contrib-modules/ga_login#4]
- [x] Allow the user to change the name prefix ( If you scan the QRCode in authenticator app the name which shows there is a combination of name prefix and your username )
- [x] Allow the user to set the secret. The secret is what we use to encrypt the seed and is not configurable at this point. This needs more research as we have to shift the whole encryption part to Encrypt module.
- [x] Show which otp method is enabled. The overview page only shows TFA enabled but not which validation TOTP or HOTP. Again fairly easy.
- [x] Delete data when setup is cancelled. The HOTP counter is saved in the database and is not deleted when the setup is cancelled. This is fairly easy.

**Comment by nerdstein** [comment]
Split into separate issues
