### ISSUE TITLE
Module needs a composer.json to support composer workflow

### ISSUE THREAD

**Issue by aweingarten** [d8-contrib-modules/ga_login#6]
D8 is moving towards replacing drush make with composer.  To support a composer based workflow this module should have a composer.json.  

Given that this is an alpha the module is probably not going to be registered on packagist or drupal's packagist.   In the interim Module should ship with instructions on how to add the module to a composer.json.

**Comment by therealssj** [comment]
@aweingarten The external libraries are handled by the TFA module which has the composer.json file.
All this module does is provided the setup classes.
Setup classes like the name handle the setting up of the validation method. Basically everyting under the security tab at `user/id/security/tfa`

**Comment by nerdstein** [comment]
I think this composer.json file is actually used for composer-based workflows in Drupal. Some Drupal 8 sites are completely managed by Composer

**Comment by nerdstein** [comment]
As such, it needs a composer.json file for the metadata of the module

**Comment by therealssj** [comment]
https://github.com/d8-contrib-modules/ga_login/pull/10
